### ISSUE TITLE
common.rb:32:in `<top (required)>': undefined method `+' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by bhoslepu** [europeana/assembla-to-jira#1]
I am trying out migrating Assemble to JIRA using code and instructions provided on README

But getting below error:
[ec2-user@ip-172-31-36-230 assembla-to-jira]$ ruby 01-assembla_export_space.rb
/home/ec2-user/assembla-to-jira/lib/common.rb:32:in `<top (required)>': undefined method `+' for nil:NilClass (NoMethodError)
        from 01-assembla_export_space.rb:3:in `load'
        from 01-assembla_export_space.rb:3:in `<main>'

Configuration:
1. Setup .env file by referring .env.example format
2. [ec2-user@ip-172-31-36-230 assembla-to-jira]$ cat .ruby-version
    2.4.1
3. [ec2-user@ip-172-31-36-230 assembla-to-jira]$ gem2.4 list

*** LOCAL GEMS ***

ast (2.3.0)
bigdecimal (1.3.2)
bundle (0.0.1)
bundler (1.17.2)
domain_name (0.5.20170404)
dotenv (2.2.1)
http-cookie (1.0.3)
io-console (0.4.6)
json (2.0.4)
mime-types (3.1)
mime-types-data (3.2016.0521)
netrc (0.11.0)
openssl (2.0.7)
parser (2.4.0.0)
power_assert (0.2.7)
powerpack (0.1.1)
psych (2.2.2)
rainbow (2.2.2)
rake (12.0.0)
rdoc (5.0.0)
rest-client (2.0.2)
rubocop (0.48.1)
ruby-progressbar (1.8.1)
test-unit (3.2.3)
unf (0.1.4)
unf_ext (0.0.7.4)
unicode-display_width (1.3.0)

[ec2-user@ip-172-31-36-230 assembla-to-jira]$ whereis gem
gem: /usr/bin/gem2.4 /usr/bin/gem2.0 /usr/bin/gem

**Comment by bhoslepu** [comment]
Fixed by correcting JIRA_HEADERS parameters.
